version: '3'
services:
  
  backend:
    build: 
      context: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      - ai
      - mongo
    networks:
      - backend_network

  ai:
    build: 
      context: ./Deployment
    ports:
      - "9000:9000"
    networks:
      - backend_network

  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_network

volumes:
  mongo-data:

networks:
  backend_network:
    driver: bridge
